In [2]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [3]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow_core._api.v2.version' from '/tensorflow-2.1.0/python3.6/tensorflow_core/_api/v2/version/__init__.py'>


In [0]:
 string = tf.Variable("this si string tensor",tf.string)
 numeric = tf.Variable(326,tf.int32)
 floating = tf.Variable(3.567,tf.float32)

In [0]:
 rank1_tensor = tf.Variable(['Test',"OK","no"],tf.string)
 rank2_tensor = tf.Variable([["Test","OK","no"],["I","Am","Legend"],["ok","ok","ok"]],tf.string)

In [11]:
tf.rank(rank2_tensor) #Rank 1 tensor

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [12]:
rank2_tensor.shape

TensorShape([3, 3])

In [14]:
tensor1 = tf.ones([1,2,3])
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [15]:
tensor2 = tf.reshape(tensor1,shape=[2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [16]:
tensor3 =tf.reshape(tensor1,shape=[3,-1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [17]:
tensor_flatten = tf.reshape(tensor1,[6])
print(tensor_flatten)

tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)


In [18]:
print(tf.reshape(tensor1,shape=[2,-1]))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
